export type LicencasProps = {
  id: number;
  nome: string;
  idPsn: string;
  carteira: string;
  cor: string;
};

export const licencas = [
  {
    id: 21,
    nome: "Gustavo Viaro",
    idPsn: "CCGTBR_Gustavo",
    carteira: "SS",
    cor: "#000",
  },
  {
    id: 5,
    nome: "João Paulo Facci",
    idPsn: "JPFACCI_SPEEDBR",
    carteira: "SS",
    cor: "#000",
  },
  {
    id: 6,
    nome: "Luis Ferruthio",
    idPsn: "FERRUTH_SPEEDBR",
    carteira: "SS",
    cor: "#000",
  },
  {
    id: 4,
    nome: "Ronald Carvalho",
    idPsn: "roonald_f1",
    carteira: "SS",
    cor: "#000",
  },
  {
    id: 3,
    nome: "José Eduardo Filho",
    idPsn: "PCR_Dudu10",
    carteira: "SS",
    cor: "#000",
  },
  {
    id: 1,
    nome: "Leonardo Guain",
    idPsn: "leoguain",
    carteira: "SS",
    cor: "#000",
  },
  {
    id: 19,
    nome: "Murilo Silva",
    idPsn: "MYTH_MuriloSilva",
    carteira: "SS",
    cor: "#000",
  },
  {
    id: 45,
    nome: "João Cláudio Pessoa",
    idPsn: "MYTH_JoaoSof",
    carteira: "SS",
    cor: "#000",
  },
  {
    id: 20,
    nome: "Eduardo Schaarschmidt",
    idPsn: "DuduToretto",
    carteira: "SS",
    cor: "#000",
  },
  {
    id: 44,
    nome: "Ednaldo Martins",
    idPsn: "KMZ_Naldo",
    carteira: "SS",
    cor: "#000",
  },
  {
    id: 36,
    nome: "Fabiano Furini",
    idPsn: "FURINI_SPEEDBR",
    carteira: "SS",
    cor: "#000",
  },
  {
    id: 38,
    nome: "Gerson Garcia",
    idPsn: "Gersão Hamilton",
    carteira: "SS",
    cor: "#000",
  },
  {
    id: 15,
    nome: "Fábian Viegas",
    idPsn: "FABIAN_SPEEDBR",
    carteira: "S",
    cor: "#049dc8",
  },
  {
    id: 2,
    nome: "Rafael Garcia",
    idPsn: "rafael_garcia79",
    carteira: "S",
    cor: "#049dc8",
  },
  {
    id: 99,
    nome: "Alessandro Albuquerque",
    idPsn: "AlêCareca",
    carteira: "S",
    cor: "#049dc8",
  },
  {
    id: 10,
    nome: "Marco Aurélio Cerqueira",
    idPsn: "Marco_RJ",
    carteira: "S",
    cor: "#049dc8",
  },
  {
    id: 47,
    nome: "Milton Garcia",
    idPsn: "KMZ-R_SGARCIA",
    carteira: "S",
    cor: "#049dc8",
  },
  {
    id: 7,
    nome: "Marco Santos",
    idPsn: "MarcodiSantti",
    carteira: "S",
    cor: "#049dc8",
  },
  {
    id: 9,
    nome: "Luis Vilches",
    idPsn: "luisvilches",
    carteira: "A",
    cor: "#00a85a",
  },
  {
    id: 48,
    nome: "Yuri Demetrius",
    idPsn: "kMz_YuriGrusH",
    carteira: "A",
    cor: "#00a85a",
  },
  {
    id: 35,
    nome: "Luan Muniz",
    idPsn: "KMZ_Luan_muniz89",
    carteira: "A",
    cor: "#00a85a",
  },
  {
    id: 25,
    nome: "Ronan C S Berto",
    idPsn: "Bertorcsb",
    carteira: "A",
    cor: "#00a85a",
  },
  {
    id: 8,
    nome: "Jeferson Luis de Souza",
    idPsn: "Jefimwn221",
    carteira: "A",
    cor: "#00a85a",
  },
  {
    id: 11,
    nome: "Paulo Henrique Monte",
    idPsn: "PRBR_PH",
    carteira: "A",
    cor: "#00a85a",
  },
  {
    id: 28,
    nome: "Cléber Carlos",
    idPsn: "CLEBER_SPEEDBR",
    carteira: "A",
    cor: "#00a85a",
  },
  {
    id: 16,
    nome: "Marco Godoi",
    idPsn: "Cel_God",
    carteira: "A",
    cor: "#00a85a",
  },
  {
    id: 32,
    nome: "Gustavo Parra",
    idPsn: "Ghustaw",
    carteira: "A",
    cor: "#00a85a",
  },
  {
    id: 23,
    nome: "Thomas Penteado",
    idPsn: "NeoCactuar",
    carteira: "A",
    cor: "#00a85a",
  },
  {
    id: 30,
    nome: "Alessandro Gratão",
    idPsn: "AleGratao76",
    carteira: "A",
    cor: "#00a85a",
  },
  {
    id: 52,
    nome: "Cláudio Faria",
    idPsn: "CCGTBR-c_faria",
    carteira: "A",
    cor: "#00a85a",
  },
  {
    id: 50,
    nome: "Cristiano Dutra",
    idPsn: "CCGTBR_Cristiano",
    carteira: "A",
    cor: "#00a85a",
  },
  {
    id: 56,
    nome: "Kelvin Carvalho",
    idPsn: "Axelkl19",
    carteira: "A",
    cor: "#00a85a",
  },
  {
    id: 12,
    nome: "Taynam Magalhães",
    idPsn: "TayMaga",
    carteira: "A",
    cor: "#00a85a",
  },
  {
    id: 24,
    nome: "Francisco E da Silva",
    idPsn: "CCGTBR-ELEKTROED",
    carteira: "A",
    cor: "#00a85a",
  },
  {
    id: 54,
    nome: "Carlos de Godoy",
    idPsn: "MF2_TattoBrown",
    carteira: "A",
    cor: "#00a85a",
  },
  {
    id: 40,
    nome: "Paulo Ramos",
    idPsn: "Paulo_baiano27",
    carteira: "A",
    cor: "#00a85a",
  },
  {
    id: 34,
    nome: "Leandro Borges",
    idPsn: "Caua-1308",
    carteira: "A",
    cor: "#00a85a",
  },
  {
    id: 41,
    nome: "Walter R de Moraes",
    idPsn: "waltinhorpm74",
    carteira: "A",
    cor: "#00a85a",
  },
  {
    id: 37,
    nome: "Lucas Zanivam Macam",
    idPsn: "KMZ_Lucas_ZM",
    carteira: "A",
    cor: "#00a85a",
  },
  {
    id: 13,
    nome: "Eduardo Alecrim",
    idPsn: "alecrim7",
    carteira: "B",
    cor: "#ec3237",
  },
  {
    id: 39,
    nome: "Thiago dos S Lima",
    idPsn: "MYTH_THIAGO_AM",
    carteira: "B",
    cor: "#ec3237",
  },
  {
    id: 31,
    nome: "Algberg Veloso",
    idPsn: "Berg_pvh",
    carteira: "B",
    cor: "#ec3237",
  },
  {
    id: 22,
    nome: "Paulo Tureck",
    idPsn: "TURECK_SPEEDBR",
    carteira: "B",
    cor: "#ec3237",
  },
  {
    id: 46,
    nome: "Pedro Bernardo",
    idPsn: "Petros_pro",
    carteira: "B",
    cor: "#ec3237",
  },
  {
    id: 18,
    nome: "Juan",
    idPsn: "DJ_CARIOCADZ7",
    carteira: "B",
    cor: "#ec3237",
  },
  {
    id: 53,
    nome: "Marco Antonio Soares",
    idPsn: "CRS_BillyBizzuca",
    carteira: "B",
    cor: "#ec3237",
  },
  {
    id: 27,
    nome: "Yuri Stolai",
    idPsn: "Punhalkiller",
    carteira: "B",
    cor: "#ec3237",
  },
  {
    id: 49,
    nome: "Marcos André da Silva",
    idPsn: "CCGTBR_Borges",
    carteira: "B",
    cor: "#ec3237",
  },
  {
    id: 55,
    nome: "Thiago Alves da Silva",
    idPsn: "Thiago_Wolf",
    carteira: "B",
    cor: "#ec3237",
  },
  {
    id: 51,
    nome: "Jonathan Diego",
    idPsn: "E-Boss_Jonathan",
    carteira: "B",
    cor: "#ec3237",
  },
  {
    id: 17,
    nome: "Rafael Leite",
    idPsn: "RafaeL1983_SCCP",
    carteira: "B",
    cor: "#ec3237",
  },
  {
    id: 42,
    nome: "Aldair Martins",
    idPsn: "Aldair_Martins",
    carteira: "B",
    cor: "#ec3237",
  },
  {
    id: 43,
    nome: "Walter G dos Santos",
    idPsn: "Walter-wa42",
    carteira: "B",
    cor: "#ec3237",
  },
  {
    id: 26,
    nome: "Luciano Braga",
    idPsn: "KymMastter-kmz",
    carteira: "B",
    cor: "#ec3237",
  },
  {
    id: 14,
    nome: "Matheus Souza",
    idPsn: "AlR_F0RCE_0NE_01",
    carteira: "B",
    cor: "#ec3237",
  },
  {
    id: 57,
    nome: "Luciano Five",
    idPsn: "lppfive",
    carteira: "B",
    cor: "#ec3237",
  },
  {
    id: 29,
    nome: "Bruno Borges",
    idPsn: "Bruno_moby",
    carteira: "B",
    cor: "#ec3237",
  },
  {
    id: 33,
    nome: "Gustavo Nery",
    idPsn: "Gustavo__Nery",
    carteira: "B",
    cor: "#ec3237",
  },
];
