import logoBVRB from './components/Assets/liga_bvr_gt_branco.png';

export type NoticiaProps = {
    id:string,
    title:string,
    data:string,
    texto:string,
    image:string,
    url:string,
};


export const noticias = [
    {id:"7",
     title:"Nova vitória da CCGTBR em Alsace",
     data:"25/10/2022",
     texto:"Não viu a corrida? Veja agora:",
     image:logoBVRB, 
     url:"https://www.youtube.com/watch?v=KjrGtETh2lY",
    },
    {id:"6",
     title:"Resultados de Alsace - Nissan Silva Kup",
     data:"24/10/2022",
     texto:"Gustavo Viaro vence a segunda etapa no circuito de Alsace - Vila. Os resultados foram divulgados hoje no Instagram da Liga, e você acompanha aqui também! Não viu a corrida? Veja agora:",
     image:logoBVRB, 
     url:"https://www.youtube.com/watch?v=KjrGtETh2lY",
    },
    {id:"5",
     title:"Resultados de Alsace - Nissan Silva Kup",
     data:"23/10/2022",
     texto:"Gustavo Viaro vence a segunda etapa no circuito de Alsace - Vila. Os resultados foram divulgados hoje no Instagram da Liga, e você acompanha aqui também! Não viu a corrida? Veja agora:",
     image:logoBVRB, 
     url:"https://www.youtube.com/watch?v=KjrGtETh2lY",
    },
    {id:"4",
     title:"Resultados de Alsace - Nissan Silva Kup",
     data:"22/10/2022",
     texto:"nononononononononon ononononononononononononono nonononononononononononon onononononononononononon ononononononononononono nonononononononon ononononono",
     image:logoBVRB, 
     url:"https://www.youtube.com/watch?v=KjrGtETh2lY",
    },
    {id:"3",
     title:"Hoje tem corrida!",
     data:"20/10/2022",
     texto:"Hoje, às 21h, acontecerá a segunda etapa do Nissan Silvia KUP! A etapa de semana passada acabou sendo adiada por problemas no jogo.",
     image:logoBVRB, 
     url:"https://www.youtube.com/c/BVGTV",
    },
    {id:"2",
     title:"Atualização nova no GT7!",
     data:"19/10/2022",
     texto:"Na madrugada do dia 20/10 haverá a atualização 1.24. Nessa atualização teremos 4 novos carros e possíveis correções do jogo. Fiquem de olho!",
     image:logoBVRB, 
     url:"https://www.youtube.com/watch?v=TYG3lfU5EoY",
    },
    {id:"1",
     title:"Inauguração do site da BVR!",
     data:"10/10/2022",
     texto:"Hoje dia XX/XX estréia o site da Liga BVR! Aqui você acompanhará todas as novidades da Liga, e o que já aconteceu desde a temporada 2021!",
     image:logoBVRB, 
     url:"https://www.youtube.com/c/BVGTV",
    },
];