export type RecordesProps = {
  IdPista: number;
  PistaEtapa: string;
  Campeonato: string;
  Ano: string;
  Plataforma: string;
  Categoria: string;
  DataEtapa: string;
  IdPilotoPole: string;
  PilotoPole: string;
  TempoPole: string;
  IdPilotoVMR: string;
  PilotoVMR: string;
  TempoVMR: string;
};

export const recordes = [
  {
    IdPista: 1,
    PistaEtapa: "Alsace",
    Campeonato: "Nissan Silvia Kup",
    Ano: "2022",
    Plataforma: "Gran Turismo 7",
    Categoria: "Nissan Silvia Gr.4",
    DataEtapa: "20/10/2022",
    IdPilotoPole: "21",
    PilotoPole: "Gustavo Viaro",
    TempoPole: "1:59.771",
    IdPilotoVMR: "21",
    PilotoVMR: "Gustavo Viaro",
    TempoVMR: "1:59.940",
  },
  {
    IdPista: 2,
    PistaEtapa: "Autódromo de Interlagos",
    Campeonato: "Multi Gr.4 $tream",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Gr.4",
    DataEtapa: "",
    IdPilotoPole: "45",
    PilotoPole: "João Cláudio Pessoa",
    TempoPole: "1:36.720",
    IdPilotoVMR: "45",
    PilotoVMR: "João Cláudio Pessoa",
    TempoVMR: "1:36.873",
  },
  {
    IdPista: 3,
    PistaEtapa: "Autódromo de Interlagos",
    Campeonato: "GT3 Cup",
    Ano: "2022",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Gr.3",
    DataEtapa: "",
    IdPilotoPole: "21",
    PilotoPole: "Gustavo Viaro",
    TempoPole: "1:31.459",
    IdPilotoVMR: "21",
    PilotoVMR: "Gustavo Viaro",
    TempoVMR: "1:32.180",
  },
  {
    IdPista: 4,
    PistaEtapa: "Autódromo de Interlagos",
    Campeonato: "Nissan Silvia Kup",
    Ano: "2022",
    Plataforma: "Gran Turismo 7",
    Categoria: "Nissan Silvia Gr.4",
    DataEtapa: "",
    IdPilotoPole: "21",
    PilotoPole: "Gustavo Viaro",
    TempoPole: "1:37.649",
    IdPilotoVMR: "21",
    PilotoVMR: "Gustavo Viaro",
    TempoVMR: "1:37.776",
  },
  {
    IdPista: 5,
    PistaEtapa: "Autodromo Monza",
    Campeonato: "Multi Gr.4 $tream",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Gr.4",
    DataEtapa: "",
    IdPilotoPole: "21",
    PilotoPole: "Gustavo Viaro",
    TempoPole: "1:56.476",
    IdPilotoVMR: "21",
    PilotoVMR: "Gustavo Viaro",
    TempoVMR: "1:56.416",
  },
  {
    IdPista: 6,
    PistaEtapa: "Autodromo Monza",
    Campeonato: "GT3 Cup",
    Ano: "2022",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Gr.3",
    DataEtapa: "",
    IdPilotoPole: "21",
    PilotoPole: "Gustavo Viaro",
    TempoPole: "1:38.436",
    IdPilotoVMR: "21",
    PilotoVMR: "Gustavo Viaro",
    TempoVMR: "1:38.282",
  },
  {
    IdPista: 7,
    PistaEtapa: "Autodromo Monza S/C",
    Campeonato: "Porsche Cup Gemignani",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Porsche RSR Gr.3",
    DataEtapa: "",
    IdPilotoPole: "4",
    PilotoPole: "Ronald Carvalho",
    TempoPole: "1:38.627",
    IdPilotoVMR: "4",
    PilotoVMR: "Ronald Carvalho",
    TempoVMR: "1:38.500",
  },
  {
    IdPista: 8,
    PistaEtapa: "Autodromo Monza S/C",
    Campeonato: "Redware GT500",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Gr.2",
    DataEtapa: "",
    IdPilotoPole: "19",
    PilotoPole: "Murilo Silva",
    TempoPole: "1:29.735",
    IdPilotoVMR: "19",
    PilotoVMR: "Murilo Silva",
    TempoVMR: "1:30.278",
  },
  {
    IdPista: 9,
    PistaEtapa: "Autopolis",
    Campeonato: "GT3 Cup",
    Ano: "2022",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Gr.3",
    DataEtapa: "",
    IdPilotoPole: "21",
    PilotoPole: "Gustavo Viaro",
    TempoPole: "1:45.881",
    IdPilotoVMR: "2",
    PilotoVMR: "Rafael Garcia",
    TempoVMR: "1:45.836",
  },
  {
    IdPista: 10,
    PistaEtapa: "Autopolis Curta",
    Campeonato: "Mazda Touring Cup",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Mazda Roadster",
    DataEtapa: "",
    IdPilotoPole: "5",
    PilotoPole: "João Paulo Facci",
    TempoPole: "1:23.248",
    IdPilotoVMR: "4",
    PilotoVMR: "Ronald Carvalho",
    TempoVMR: "1:23.155",
  },
  {
    IdPista: 11,
    PistaEtapa: "Autopolis Curta",
    Campeonato: "Toyota $tream Light",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Toyota SF-R",
    DataEtapa: "",
    IdPilotoPole: "4",
    PilotoPole: "Ronald Carvalho",
    TempoPole: "1:16.760",
    IdPilotoVMR: "39",
    PilotoVMR: "Thiago dos S Lima",
    TempoVMR: "1:16.927",
  },
  {
    IdPista: 12,
    PistaEtapa: "Autopolis Inter.",
    Campeonato: "Porsche Cup Gemignani",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Porsche RSR Gr.3",
    DataEtapa: "",
    IdPilotoPole: "2",
    PilotoPole: "Rafael Garcia",
    TempoPole: "1:45.101",
    IdPilotoVMR: "3",
    PilotoVMR: "José Eduardo Filho",
    TempoVMR: "1:45.351",
  },
  {
    IdPista: 13,
    PistaEtapa: "BB Raceway",
    Campeonato: "Toyota $tream Light",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Toyota SF-R",
    DataEtapa: "",
    IdPilotoPole: "29",
    PilotoPole: "Bruno Borges",
    TempoPole: "0:32.027",
    IdPilotoVMR: "36",
    PilotoVMR: "Fabiano Furini",
    TempoVMR: "0:32.321",
  },
  {
    IdPista: 14,
    PistaEtapa: "Big Willow",
    Campeonato: "Multi Gr.4 $tream",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Gr.4",
    DataEtapa: "",
    IdPilotoPole: "45",
    PilotoPole: "João Cláudio Pessoa",
    TempoPole: "1:15.794",
    IdPilotoVMR: "45",
    PilotoVMR: "João Cláudio Pessoa",
    TempoVMR: "1:15.979",
  },
  {
    IdPista: 15,
    PistaEtapa: "Blue Moon A",
    Campeonato: "Nissan Silvia Kup",
    Ano: "2022",
    Plataforma: "Gran Turismo 7",
    Categoria: "Nissan Silvia Gr.4",
    DataEtapa: "",
    IdPilotoPole: "36",
    PilotoPole: "Fabiano Furini",
    TempoPole: "1:12.364",
    IdPilotoVMR: "21",
    PilotoVMR: "Gustavo Viaro",
    TempoVMR: "1:12.357",
  },
  {
    IdPista: 16,
    PistaEtapa: "Blue Moon Speedway",
    Campeonato: "Multi Gr.4 $tream",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Gr.4",
    DataEtapa: "",
    IdPilotoPole: "21",
    PilotoPole: "Gustavo Viaro",
    TempoPole: "1:11.778",
    IdPilotoVMR: "45",
    PilotoVMR: "João Cláudio Pessoa",
    TempoVMR: "1:10.716",
  },
  {
    IdPista: 17,
    PistaEtapa: "Blue Moon Speedway",
    Campeonato: "GT3 Cup",
    Ano: "2022",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Gr.3",
    DataEtapa: "",
    IdPilotoPole: "38",
    PilotoPole: "Gerson Garcia",
    TempoPole: "0:43.312",
    IdPilotoVMR: "44",
    PilotoVMR: "Ednaldo Martins",
    TempoVMR: "0:43.830",
  },
  {
    IdPista: 18,
    PistaEtapa: "Blue Moon Speedway",
    Campeonato: "Nascar Series Cup",
    Ano: "2022",
    Plataforma: "Gran Turismo 7",
    Categoria: "Camaro ZL1",
    DataEtapa: "",
    IdPilotoPole: "21",
    PilotoPole: "Gustavo Viaro",
    TempoPole: "0:43.399",
    IdPilotoVMR: "21",
    PilotoVMR: "Gustavo Viaro",
    TempoVMR: "0:43.640",
  },
  {
    IdPista: 19,
    PistaEtapa: "Brands Hatch",
    Campeonato: "BMW $tream Challenge",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "BMW M3 Evolution 89",
    DataEtapa: "",
    IdPilotoPole: "4",
    PilotoPole: "Ronald Carvalho",
    TempoPole: "1:45.787",
    IdPilotoVMR: "4",
    PilotoVMR: "Ronald Carvalho",
    TempoVMR: "1:45.595",
  },
  {
    IdPista: 20,
    PistaEtapa: "Catalunha",
    Campeonato: "Multi Gr.4 $tream",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Gr.4",
    DataEtapa: "",
    IdPilotoPole: "21",
    PilotoPole: "Gustavo Viaro",
    TempoPole: "1:51.631",
    IdPilotoVMR: "45",
    PilotoVMR: "João Cláudio Pessoa",
    TempoVMR: "1:50.507",
  },
  {
    IdPista: 21,
    PistaEtapa: "Daytona Road",
    Campeonato: "Nascar Series Cup",
    Ano: "2022",
    Plataforma: "Gran Turismo 7",
    Categoria: "Camaro ZL1",
    DataEtapa: "",
    IdPilotoPole: "21",
    PilotoPole: "Gustavo Viaro",
    TempoPole: "1:42.684",
    IdPilotoVMR: "21",
    PilotoVMR: "Gustavo Viaro",
    TempoVMR: "1:43.209",
  },
  {
    IdPista: 22,
    PistaEtapa: "Daytona Tri-Oval",
    Campeonato: "Nascar Series Cup",
    Ano: "2022",
    Plataforma: "Gran Turismo 7",
    Categoria: "Camaro ZL1",
    DataEtapa: "",
    IdPilotoPole: "44",
    PilotoPole: "Ednaldo Martins",
    TempoPole: "0:41.485",
    IdPilotoVMR: "47",
    PilotoVMR: "Milton Garcia",
    TempoVMR: "0:41.739",
  },
  {
    IdPista: 23,
    PistaEtapa: "Deep Forest",
    Campeonato: "Nissan Silvia Kup",
    Ano: "2022",
    Plataforma: "Gran Turismo 7",
    Categoria: "Nissan Silvia Gr.4",
    DataEtapa: "",
    IdPilotoPole: "44",
    PilotoPole: "Ednaldo Martins",
    TempoPole: "1:33.642",
    IdPilotoVMR: "21",
    PilotoVMR: "Gustavo Viaro",
    TempoVMR: "1:33.572",
  },
  {
    IdPista: 24,
    PistaEtapa: "Fuji Curta",
    Campeonato: "Toyota $tream Light",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Toyota SF-R",
    DataEtapa: "",
    IdPilotoPole: "38",
    PilotoPole: "Gerson Garcia",
    TempoPole: "1:48.381",
    IdPilotoVMR: "6",
    PilotoVMR: "Luis Ferruthio",
    TempoVMR: "1:48.679",
  },
  {
    IdPista: 25,
    PistaEtapa: "Fuji Speedway",
    Campeonato: "Porsche Cup Gemignani",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Porsche RSR Gr.3",
    DataEtapa: "",
    IdPilotoPole: "4",
    PilotoPole: "Ronald Carvalho",
    TempoPole: "1:37.789",
    IdPilotoVMR: "4",
    PilotoVMR: "Ronald Carvalho",
    TempoVMR: "1:37.811",
  },
  {
    IdPista: 26,
    PistaEtapa: "Goodwood",
    Campeonato: "BMW $tream Challenge",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "BMW M3 Evolution 89",
    DataEtapa: "",
    IdPilotoPole: "25",
    PilotoPole: "Ronan C S Berto",
    TempoPole: "1:28.499",
    IdPilotoVMR: "25",
    PilotoVMR: "Ronan C S Berto",
    TempoVMR: "1:28.608",
  },
  {
    IdPista: 27,
    PistaEtapa: "High Speed Ring",
    Campeonato: "Nascar Series Cup",
    Ano: "2022",
    Plataforma: "Gran Turismo 7",
    Categoria: "Camaro ZL1",
    DataEtapa: "",
    IdPilotoPole: "36",
    PilotoPole: "Fabiano Furini",
    TempoPole: "1:05.247",
    IdPilotoVMR: "47",
    PilotoVMR: "Milton Garcia",
    TempoVMR: "1:05.306",
  },
  {
    IdPista: 28,
    PistaEtapa: "Horse Thief Mile",
    Campeonato: "Mazda Touring Mini Cup",
    Ano: "2022",
    Plataforma: "Gran Turismo 7",
    Categoria: "Mazda Roadster",
    DataEtapa: "",
    IdPilotoPole: "6",
    PilotoPole: "Luis Ferruthio",
    TempoPole: "0:56.032",
    IdPilotoVMR: "5",
    PilotoVMR: "João Paulo Facci",
    TempoVMR: "0:56.717",
  },

  {
    IdPista: 29,
    PistaEtapa: "Kyoto Miyabi",
    Campeonato: "Mazda Touring Cup",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Mazda Roadster",
    DataEtapa: "",
    IdPilotoPole: "2",
    PilotoPole: "Rafael Garcia",
    TempoPole: "0:45.746",
    IdPilotoVMR: "2",
    PilotoVMR: "Rafael Garcia",
    TempoVMR: "0:45.935",
  },
  {
    IdPista: 30,
    PistaEtapa: "Kyoto Yamagiwa",
    Campeonato: "Toyota $tream Light",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Toyota SF-R",
    DataEtapa: "",
    IdPilotoPole: "6",
    PilotoPole: "Luis Ferruthio",
    TempoPole: "1:47.853",
    IdPilotoVMR: "6",
    PilotoVMR: "Luis Ferruthio",
    TempoVMR: "1:47.933",
  },
  {
    IdPista: 31,
    PistaEtapa: "Kyoto Yamagiwa + Miyabi",
    Campeonato: "Redware GT500",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Gr.2",
    DataEtapa: "",
    IdPilotoPole: "19",
    PilotoPole: "Murilo Silva",
    TempoPole: "2:04.764",
    IdPilotoVMR: "19",
    PilotoVMR: "Murilo Silva",
    TempoVMR: "2:04.152",
  },
  {
    IdPista: 32,
    PistaEtapa: "La Sarthe",
    Campeonato: "Redware GT500",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Gr.2",
    DataEtapa: "",
    IdPilotoPole: "19",
    PilotoPole: "Murilo Silva",
    TempoPole: "3:35.903",
    IdPilotoVMR: "21",
    PilotoVMR: "Gustavo Viaro",
    TempoVMR: "3:35.739",
  },
  {
    IdPista: 33,
    PistaEtapa: "Lago Maggiore C",
    Campeonato: "Mazda Touring Cup",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Mazda Roadster",
    DataEtapa: "",
    IdPilotoPole: "3",
    PilotoPole: "José Eduardo Filho",
    TempoPole: "0:55.051",
    IdPilotoVMR: "4",
    PilotoVMR: "Ronald Carvalho",
    TempoVMR: "0:55.249",
  },
  {
    IdPista: 34,
    PistaEtapa: "Lago Maggiore L",
    Campeonato: "Porsche Cup Gemignani",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Porsche RSR Gr.3",
    DataEtapa: "",
    IdPilotoPole: "4",
    PilotoPole: "Ronald Carvalho",
    TempoPole: "1:17.264",
    IdPilotoVMR: "4",
    PilotoVMR: "Ronald Carvalho",
    TempoVMR: "1:17.664",
  },
  {
    IdPista: 35,
    PistaEtapa: "Lago Maggiore O II",
    Campeonato: "BMW $tream Challenge",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "BMW M3 Evolution 89",
    DataEtapa: "",
    IdPilotoPole: "13",
    PilotoPole: "Eduardo Alecrim",
    TempoPole: "1:44.696",
    IdPilotoVMR: "25",
    PilotoVMR: "Ronan C S Berto",
    TempoVMR: "1:45.052",
  },
  {
    IdPista: 36,
    PistaEtapa: "Laguna Seca",
    Campeonato: "Mazda Touring Cup",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Mazda Roadster",
    DataEtapa: "",
    IdPilotoPole: "5",
    PilotoPole: "João Paulo Facci",
    TempoPole: "1:40.952",
    IdPilotoVMR: "4",
    PilotoVMR: "Ronald Carvalho",
    TempoVMR: "1:41.164",
  },
  {
    IdPista: 37,
    PistaEtapa: "Laguna Seca",
    Campeonato: "GT3 Cup",
    Ano: "2022",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Gr.3",
    DataEtapa: "",
    IdPilotoPole: "3",
    PilotoPole: "José Eduardo Filho",
    TempoPole: "1:22.290",
    IdPilotoVMR: "3",
    PilotoVMR: "José Eduardo Filho",
    TempoVMR: "1:22.291",
  },
  {
    IdPista: 38,
    PistaEtapa: "Laguna Seca",
    Campeonato: "Nascar Series Cup",
    Ano: "2022",
    Plataforma: "Gran Turismo 7",
    Categoria: "Camaro ZL1",
    DataEtapa: "",
    IdPilotoPole: "47",
    PilotoPole: "Milton Garcia",
    TempoPole: "1:21.931",
    IdPilotoVMR: "47",
    PilotoVMR: "Milton Garcia",
    TempoVMR: "1:23.216",
  },
  {
    IdPista: 39,
    PistaEtapa: "Mount Panorama",
    Campeonato: "Porsche Cup Gemignani",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Porsche RSR Gr.3",
    DataEtapa: "",
    IdPilotoPole: "4",
    PilotoPole: "Ronald Carvalho",
    TempoPole: "2:02.189",
    IdPilotoVMR: "4",
    PilotoVMR: "Ronald Carvalho",
    TempoVMR: "2:02.463",
  },
  {
    IdPista: 40,
    PistaEtapa: "Mount Panorama",
    Campeonato: "Redware GT500",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Gr.2",
    DataEtapa: "",
    IdPilotoPole: "19",
    PilotoPole: "Murilo Silva",
    TempoPole: "1:51.219",
    IdPilotoVMR: "19",
    PilotoVMR: "Murilo Silva",
    TempoVMR: "1:52.084",
  },
  {
    IdPista: 41,
    PistaEtapa: "Mount Panorama",
    Campeonato: "GT3 Cup",
    Ano: "2022",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Gr.3",
    DataEtapa: "",
    IdPilotoPole: "21",
    PilotoPole: "Gustavo Viaro",
    TempoPole: "-",
    IdPilotoVMR: "21",
    PilotoVMR: "Gustavo Viaro",
    TempoVMR: "2:03.085",
  },
  {
    IdPista: 42,
    PistaEtapa: "Nürburgring 24H",
    Campeonato: "GT3 Cup",
    Ano: "2022",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Gr.3",
    DataEtapa: "",
    IdPilotoPole: "21",
    PilotoPole: "Gustavo Viaro",
    TempoPole: "8:15.670",
    IdPilotoVMR: "21",
    PilotoVMR: "Gustavo Viaro",
    TempoVMR: "8:16.617",
  },
  {
    IdPista: 43,
    PistaEtapa: "Nurburgring GP",
    Campeonato: "BMW $tream Challenge",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "BMW M3 Evolution 89",
    DataEtapa: "",
    IdPilotoPole: "13",
    PilotoPole: "Eduardo Alecrim",
    TempoPole: "2:28.236",
    IdPilotoVMR: "13",
    PilotoVMR: "Eduardo Alecrim",
    TempoVMR: "2:27.996",
  },
  {
    IdPista: 44,
    PistaEtapa: "Red Bull Ring",
    Campeonato: "Porsche Cup Gemignani",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Porsche RSR Gr.3",
    DataEtapa: "",
    IdPilotoPole: "4",
    PilotoPole: "Ronald Carvalho",
    TempoPole: "1:39.766",
    IdPilotoVMR: "4",
    PilotoVMR: "Ronald Carvalho",
    TempoVMR: "1:39.655",
  },
  {
    IdPista: 45,
    PistaEtapa: "Red Bull Ring",
    Campeonato: "Multi Gr.4 $tream",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Gr.4",
    DataEtapa: "",
    IdPilotoPole: "2",
    PilotoPole: "Rafael Garcia",
    TempoPole: "1:35.799",
    IdPilotoVMR: "21",
    PilotoVMR: "Gustavo Viaro",
    TempoVMR: "1:35.796",
  },
  {
    IdPista: 46,
    PistaEtapa: "Red Bull Ring C",
    Campeonato: "BMW $tream Challenge",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "BMW M3 Evolution 89",
    DataEtapa: "",
    IdPilotoPole: "4",
    PilotoPole: "Ronald Carvalho",
    TempoPole: "1:01.670",
    IdPilotoVMR: "4",
    PilotoVMR: "Ronald Carvalho",
    TempoVMR: "1:01.961",
  },
  {
    IdPista: 47,
    PistaEtapa: "Saint Croix A",
    Campeonato: "Redware GT500",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Gr.2",
    DataEtapa: "",
    IdPilotoPole: "21",
    PilotoPole: "Gustavo Viaro",
    TempoPole: "-",
    IdPilotoVMR: "21",
    PilotoVMR: "Gustavo Viaro",
    TempoVMR: "-",
  },
  {
    IdPista: 48,
    PistaEtapa: "Sardegna A II",
    Campeonato: "Porsche Cup Gemignani",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Porsche RSR Gr.3",
    DataEtapa: "",
    IdPilotoPole: "4",
    PilotoPole: "Ronald Carvalho",
    TempoPole: "-",
    IdPilotoVMR: "3",
    PilotoVMR: "José Eduardo Filho",
    TempoVMR: "-",
  },
  {
    IdPista: 49,
    PistaEtapa: "Sardegna C",
    Campeonato: "Mazda Touring Cup",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Mazda Roadster",
    DataEtapa: "",
    IdPilotoPole: "4",
    PilotoPole: "Ronald Carvalho",
    TempoPole: "1:06.493",
    IdPilotoVMR: "15",
    PilotoVMR: "Fábian Viegas",
    TempoVMR: "1:06.806",
  },
  {
    IdPista: 50,
    PistaEtapa: "Sardegna C",
    Campeonato: "Mazda Touring Mini Cup",
    Ano: "2022",
    Plataforma: "Gran Turismo 7",
    Categoria: "Mazda Roadster",
    DataEtapa: "",
    IdPilotoPole: "21",
    PilotoPole: "Gustavo Viaro",
    TempoPole: "1:01.272",
    IdPilotoVMR: "4",
    PilotoVMR: "Ronald Carvalho",
    TempoVMR: "1:01.928",
  },
  {
    IdPista: 51,
    PistaEtapa: "Sardegna C II",
    Campeonato: "BMW $tream Challenge",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "BMW M3 Evolution 89",
    DataEtapa: "",
    IdPilotoPole: "25",
    PilotoPole: "Ronan C S Berto",
    TempoPole: "1:07.204",
    IdPilotoVMR: "25",
    PilotoVMR: "Ronan C S Berto",
    TempoVMR: "1:07.348",
  },
  {
    IdPista: 52,
    PistaEtapa: "Spa",
    Campeonato: "Porsche Cup Gemignani",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Porsche RSR Gr.3",
    DataEtapa: "",
    IdPilotoPole: "6",
    PilotoPole: "Luis Ferruthio",
    TempoPole: "2:18.287",
    IdPilotoVMR: "7",
    PilotoVMR: "Marco Santos",
    TempoVMR: "2:17.932",
  },
  {
    IdPista: 53,
    PistaEtapa: "Spa",
    Campeonato: "Redware GT500",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Gr.2",
    DataEtapa: "",
    IdPilotoPole: "21",
    PilotoPole: "Gustavo Viaro",
    TempoPole: "2:24.195",
    IdPilotoVMR: "21",
    PilotoVMR: "Gustavo Viaro",
    TempoVMR: "2:24.744",
  },
  {
    IdPista: 54,
    PistaEtapa: "Spa",
    Campeonato: "GT3 Cup",
    Ano: "2022",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Gr.3",
    DataEtapa: "",
    IdPilotoPole: "3",
    PilotoPole: "José Eduardo Filho",
    TempoPole: "2:18.331",
    IdPilotoVMR: "3",
    PilotoVMR: "José Eduardo Filho",
    TempoVMR: "2:19.370",
  },
  {
    IdPista: 55,
    PistaEtapa: "Suzuka Circuit",
    Campeonato: "Toyota $tream Light",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Toyota SF-R",
    DataEtapa: "",
    IdPilotoPole: "5",
    PilotoPole: "João Paulo Facci",
    TempoPole: "2:18.057",
    IdPilotoVMR: "44",
    PilotoVMR: "Ednaldo Martins",
    TempoVMR: "2:19.403",
  },
  {
    IdPista: 56,
    PistaEtapa: "Suzuka Circuit",
    Campeonato: "Nissan Silvia Kup",
    Ano: "2022",
    Plataforma: "Gran Turismo 7",
    Categoria: "Nissan Silvia Gr.4",
    DataEtapa: "",
    IdPilotoPole: "36",
    PilotoPole: "Fabiano Furini",
    TempoPole: "2:09.471",
    IdPilotoVMR: "21",
    PilotoVMR: "Gustavo Viaro",
    TempoVMR: "2:09.781",
  },
  {
    IdPista: 57,
    PistaEtapa: "Suzuka Leste",
    Campeonato: "Mazda Touring Cup",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Mazda Roadster",
    DataEtapa: "",
    IdPilotoPole: "3",
    PilotoPole: "José Eduardo Filho",
    TempoPole: "0:58.501",
    IdPilotoVMR: "6",
    PilotoVMR: "Luis Ferruthio",
    TempoVMR: "0:58.663",
  },
  {
    IdPista: 58,
    PistaEtapa: "Tokyo Exp. Sul R",
    Campeonato: "Nissan Silvia Kup",
    Ano: "2022",
    Plataforma: "Gran Turismo 7",
    Categoria: "Nissan Silvia Gr.4",
    DataEtapa: "",
    IdPilotoPole: "6",
    PilotoPole: "Luis Ferruthio",
    TempoPole: "2:06.584",
    IdPilotoVMR: "21",
    PilotoVMR: "Gustavo Viaro",
    TempoVMR: "2:06.205",
  },
  {
    IdPista: 59,
    PistaEtapa: "Trial Mountain",
    Campeonato: "Mazda Touring Mini Cup",
    Ano: "2022",
    Plataforma: "Gran Turismo 7",
    Categoria: "Mazda Roadster",
    DataEtapa: "",
    IdPilotoPole: "5",
    PilotoPole: "João Paulo Facci",
    TempoPole: "2:10.574",
    IdPilotoVMR: "21",
    PilotoVMR: "Gustavo Viaro",
    TempoVMR: "2:12.229",
  },
  {
    IdPista: 60,
    PistaEtapa: "Tsukuba Circuit",
    Campeonato: "Toyota $tream Light",
    Ano: "2021",
    Plataforma: "Gran Turismo Sport",
    Categoria: "Toyota SF-R",
    DataEtapa: "",
    IdPilotoPole: "38",
    PilotoPole: "Gerson Garcia",
    TempoPole: "1:01.229",
    IdPilotoVMR: "36",
    PilotoVMR: "Fabiano Furini",
    TempoVMR: "1:01.276",
  },
  {
    IdPista: 61,
    PistaEtapa: "Tsukuba Circuit",
    Campeonato: "Mazda Touring Mini Cup",
    Ano: "2022",
    Plataforma: "Gran Turismo 7",
    Categoria: "Mazda Roadster",
    DataEtapa: "",
    IdPilotoPole: "21",
    PilotoPole: "Gustavo Viaro",
    TempoPole: "1:01.556",
    IdPilotoVMR: "6",
    PilotoVMR: "Luis Ferruthio",
    TempoVMR: "1:02.356",
  },
  {
    IdPista: 62,
    PistaEtapa: "Watkins Glen Curta",
    Campeonato: "Nascar Series Cup",
    Ano: "2022",
    Plataforma: "Gran Turismo 7",
    Categoria: "Camaro ZL1",
    DataEtapa: "",
    IdPilotoPole: "47",
    PilotoPole: "Milton Garcia",
    TempoPole: "1:06.882",
    IdPilotoVMR: "21",
    PilotoVMR: "Gustavo Viaro",
    TempoVMR: "1:06.887",
  },
];
