export type ResultadosProps = {
  nomeCampeonato: string;
  ano: string;
  logoCampeonato: string;
  corBkg: string;
  corHead: string;
  corRow: string;
  corTxt: string;
  idPiloto: string;
  nomePiloto: string;
  idPsn: string;
  totalPontos: number;
  posicao: string;
};

export const ultimosResultadosEtapa = [
  {
    nomeCampeonato: "Nissan Silvia Kup",
    ano: "2022",
    logoCampeonato: "logoSilviaKupRed2022.png",
    corBkg: "#e9e9e9",
    corHead: "#bc0202",
    corRow: "#c7c7c7",
    corTxt: "#bc0202",
    idPiloto: "",
    nomePiloto: "Fabiano Furini",
    idPsn: "FURINI_SPEEDBR",
    totalPontos: 30,
    posicao: "1",
  },
  {
    nomeCampeonato: "Nissan Silvia Kup",
    ano: "2022",
    logoCampeonato: "logoSilviaKupRed2022.png",
    corBkg: "#e9e9e9",
    corHead: "#bc0202",
    corRow: "#c7c7c7",
    corTxt: "#bc0202",
    idPiloto: "",
    nomePiloto: "Gustavo Viaro",
    idPsn: "CCGTBR_Gustavo",
    totalPontos: 25,
    posicao: "2",
  },
  {
    nomeCampeonato: "Nissan Silvia Kup",
    ano: "2022",
    logoCampeonato: "logoSilviaKupRed2022.png",
    corBkg: "#e9e9e9",
    corHead: "#bc0202",
    corRow: "#c7c7c7",
    corTxt: "#bc0202",
    idPiloto: "",
    nomePiloto: "Gerson Garcia",
    idPsn: "Gersão Hamilton",
    totalPontos: 21,
    posicao: "3",
  },
  {
    nomeCampeonato: "Nissan Silvia Kup",
    ano: "2022",
    logoCampeonato: "logoSilviaKupRed2022.png",
    corBkg: "#e9e9e9",
    corHead: "#bc0202",
    corRow: "#c7c7c7",
    corTxt: "#bc0202",
    idPiloto: "",
    nomePiloto: "Ednaldo Martins",
    idPsn: "KMZ_Naldo",
    totalPontos: 18,
    posicao: "4",
  },
  {
    nomeCampeonato: "Nissan Silvia Kup",
    ano: "2022",
    logoCampeonato: "logoSilviaKupRed2022.png",
    corBkg: "#e9e9e9",
    corHead: "#bc0202",
    corRow: "#c7c7c7",
    corTxt: "#bc0202",
    idPiloto: "",
    nomePiloto: "Kelvin Carvalho",
    idPsn: "Axelkl19",
    totalPontos: 15,
    posicao: "5",
  },
  {
    nomeCampeonato: "Nissan Silvia Kup",
    ano: "2022",
    logoCampeonato: "logoSilviaKupRed2022.png",
    corBkg: "#e9e9e9",
    corHead: "#bc0202",
    corRow: "#c7c7c7",
    corTxt: "#bc0202",
    idPiloto: "",
    nomePiloto: "Luan Muniz",
    idPsn: "KMZ_Luan_muniz89",
    totalPontos: 12,
    posicao: "6",
  },
  {
    nomeCampeonato: "Nissan Silvia Kup",
    ano: "2022",
    logoCampeonato: "logoSilviaKupRed2022.png",
    corBkg: "#e9e9e9",
    corHead: "#bc0202",
    corRow: "#c7c7c7",
    corTxt: "#bc0202",
    idPiloto: "",
    nomePiloto: "Yuri Demetrius",
    idPsn: "kMz_YuriGrusH",
    totalPontos: 10,
    posicao: "7",
  },
  {
    nomeCampeonato: "Nissan Silvia Kup",
    ano: "2022",
    logoCampeonato: "logoSilviaKupRed2022.png",
    corBkg: "#e9e9e9",
    corHead: "#bc0202",
    corRow: "#c7c7c7",
    corTxt: "#bc0202",
    idPiloto: "",
    nomePiloto: "Cristiano Dutra",
    idPsn: "CCGTBR_Cristiano",
    totalPontos: 8,
    posicao: "8",
  },
  {
    nomeCampeonato: "Nissan Silvia Kup",
    ano: "2022",
    logoCampeonato: "logoSilviaKupRed2022.png",
    corBkg: "#e9e9e9",
    corHead: "#bc0202",
    corRow: "#c7c7c7",
    corTxt: "#bc0202",
    idPiloto: "",
    nomePiloto: "Carlos Celso de Godoy",
    idPsn: "MF2_TattoBrown",
    totalPontos: 7,
    posicao: "9",
  },
  {
    nomeCampeonato: "Nissan Silvia Kup",
    ano: "2022",
    logoCampeonato: "logoSilviaKupRed2022.png",
    corBkg: "#e9e9e9",
    corHead: "#bc0202",
    corRow: "#c7c7c7",
    corTxt: "#bc0202",
    idPiloto: "",
    nomePiloto: "Cláudio Faria",
    idPsn: "CCGTBR-c_faria",
    totalPontos: 6,
    posicao: "10",
  },
  {
    nomeCampeonato: "Nissan Silvia Kup",
    ano: "2022",
    logoCampeonato: "logoSilviaKupRed2022.png",
    corBkg: "#e9e9e9",
    corHead: "#bc0202",
    corRow: "#c7c7c7",
    corTxt: "#bc0202",
    idPiloto: "",
    nomePiloto: "Luis Ferruthio",
    idPsn: "FERRUTH_SPEEDBR",
    totalPontos: 5,
    posicao: "11",
  },
  {
    nomeCampeonato: "Nissan Silvia Kup",
    ano: "2022",
    logoCampeonato: "logoSilviaKupRed2022.png",
    corBkg: "#e9e9e9",
    corHead: "#bc0202",
    corRow: "#c7c7c7",
    corTxt: "#bc0202",
    idPiloto: "",
    nomePiloto: "Fábian Viegas",
    idPsn: "FABIAN_SPEEDBR",
    totalPontos: 0,
    posicao: "DNF",
  },
  {
    nomeCampeonato: "Nissan Silvia Kup",
    ano: "2022",
    logoCampeonato: "logoSilviaKupRed2022.png",
    corBkg: "#e9e9e9",
    corHead: "#bc0202",
    corRow: "#c7c7c7",
    corTxt: "#bc0202",
    idPiloto: "",
    nomePiloto: "João Paulo Facci",
    idPsn: "JPFACCI_SPEEDBR",
    totalPontos: 0,
    posicao: "NP",
  },
  {
    nomeCampeonato: "Nissan Silvia Kup",
    ano: "2022",
    logoCampeonato: "logoSilviaKupRed2022.png",
    corBkg: "#e9e9e9",
    corHead: "#bc0202",
    corRow: "#c7c7c7",
    corTxt: "#bc0202",
    idPiloto: "",
    nomePiloto: "Thiago Alves da Silva",
    idPsn: "Thiago_Wolf",
    totalPontos: 0,
    posicao: "NP",
  },
];

export const ultimosResultadosGeral = [
  {
    nomeCampeonato: "Nissan Silvia Kup",
    ano: "2022",
    logoCampeonato: "logoSilviaKupRed2022.png",
    corBkg: "#e9e9e9",
    corHead: "#bc0202",
    corRow: "#c7c7c7",
    corTxt: "#bc0202",
    idPiloto: "",
    nomePiloto: "Gustavo Viaro",
    idPsn: "CCGTBR_Gustavo",
    totalPontos: 145,
    posicao: "1",
  },
  {
    nomeCampeonato: "Nissan Silvia Kup",
    ano: "2022",
    logoCampeonato: "logoSilviaKupRed2022.png",
    corBkg: "#e9e9e9",
    corHead: "#bc0202",
    corRow: "#c7c7c7",
    corTxt: "#bc0202",
    idPiloto: "",
    nomePiloto: "João Paulo Facci",
    idPsn: "JPFACCI_SPEEDBR",
    totalPontos: 105,
    posicao: "2",
  },
  {
    nomeCampeonato: "Nissan Silvia Kup",
    ano: "2022",
    logoCampeonato: "logoSilviaKupRed2022.png",
    corBkg: "#e9e9e9",
    corHead: "#bc0202",
    corRow: "#c7c7c7",
    corTxt: "#bc0202",
    idPiloto: "",
    nomePiloto: "Fabiano Furini",
    idPsn: "FURINI_SPEEDBR",
    totalPontos: 96,
    posicao: "3",
  },
  {
    nomeCampeonato: "Nissan Silvia Kup",
    ano: "2022",
    logoCampeonato: "logoSilviaKupRed2022.png",
    corBkg: "#e9e9e9",
    corHead: "#bc0202",
    corRow: "#c7c7c7",
    corTxt: "#bc0202",
    idPiloto: "",
    nomePiloto: "Ednaldo Martins",
    idPsn: "KMZ_Naldo",
    totalPontos: 88,
    posicao: "4",
  },
  {
    nomeCampeonato: "Nissan Silvia Kup",
    ano: "2022",
    logoCampeonato: "logoSilviaKupRed2022.png",
    corBkg: "#e9e9e9",
    corHead: "#bc0202",
    corRow: "#c7c7c7",
    corTxt: "#bc0202",
    idPiloto: "",
    nomePiloto: "Fábian Viegas",
    idPsn: "FABIAN_SPEEDBR",
    totalPontos: 79,
    posicao: "5",
  },
  {
    nomeCampeonato: "Nissan Silvia Kup",
    ano: "2022",
    logoCampeonato: "logoSilviaKupRed2022.png",
    corBkg: "#e9e9e9",
    corHead: "#bc0202",
    corRow: "#c7c7c7",
    corTxt: "#bc0202",
    idPiloto: "",
    nomePiloto: "Gerson Garcia",
    idPsn: "Gersão Hamilton",
    totalPontos: 74,
    posicao: "6",
  },
  {
    nomeCampeonato: "Nissan Silvia Kup",
    ano: "2022",
    logoCampeonato: "logoSilviaKupRed2022.png",
    corBkg: "#e9e9e9",
    corHead: "#bc0202",
    corRow: "#c7c7c7",
    corTxt: "#bc0202",
    idPiloto: "",
    nomePiloto: "Kelvin Carvalho",
    idPsn: "Axelkl19",
    totalPontos: 60,
    posicao: "7",
  },
  {
    nomeCampeonato: "Nissan Silvia Kup",
    ano: "2022",
    logoCampeonato: "logoSilviaKupRed2022.png",
    corBkg: "#e9e9e9",
    corHead: "#bc0202",
    corRow: "#c7c7c7",
    corTxt: "#bc0202",
    idPiloto: "",
    nomePiloto: "Luan Muniz",
    idPsn: "KMZ_Luan_muniz89",
    totalPontos: 52,
    posicao: "8",
  },
  {
    nomeCampeonato: "Nissan Silvia Kup",
    ano: "2022",
    logoCampeonato: "logoSilviaKupRed2022.png",
    corBkg: "#e9e9e9",
    corHead: "#bc0202",
    corRow: "#c7c7c7",
    corTxt: "#bc0202",
    idPiloto: "",
    nomePiloto: "Yuri Demetrius",
    idPsn: "kMz_YuriGrusH",
    totalPontos: 51,
    posicao: "9",
  },
  {
    nomeCampeonato: "Nissan Silvia Kup",
    ano: "2022",
    logoCampeonato: "logoSilviaKupRed2022.png",
    corBkg: "#e9e9e9",
    corHead: "#bc0202",
    corRow: "#c7c7c7",
    corTxt: "#bc0202",
    idPiloto: "",
    nomePiloto: "Carlos Celso de Godoy",
    idPsn: "MF2_TattoBrown",
    totalPontos: 30,
    posicao: "10",
  },
  {
    nomeCampeonato: "Nissan Silvia Kup",
    ano: "2022",
    logoCampeonato: "logoSilviaKupRed2022.png",
    corBkg: "#e9e9e9",
    corHead: "#bc0202",
    corRow: "#c7c7c7",
    corTxt: "#bc0202",
    idPiloto: "",
    nomePiloto: "Cláudio Faria",
    idPsn: "CCGTBR-c_faria",
    totalPontos: 29,
    posicao: "11",
  },
  {
    nomeCampeonato: "Nissan Silvia Kup",
    ano: "2022",
    logoCampeonato: "logoSilviaKupRed2022.png",
    corBkg: "#e9e9e9",
    corHead: "#bc0202",
    corRow: "#c7c7c7",
    corTxt: "#bc0202",
    idPiloto: "",
    nomePiloto: "Cristiano Dutra",
    idPsn: "CCGTBR_Cristiano",
    totalPontos: 27,
    posicao: "12",
  },
  {
    nomeCampeonato: "Nissan Silvia Kup",
    ano: "2022",
    logoCampeonato: "logoSilviaKupRed2022.png",
    corBkg: "#e9e9e9",
    corHead: "#bc0202",
    corRow: "#c7c7c7",
    corTxt: "#bc0202",
    idPiloto: "",
    nomePiloto: "Luis Ferruthio",
    idPsn: "FERRUTH_SPEEDBR",
    totalPontos: 21,
    posicao: "13",
  },
  {
    nomeCampeonato: "Nissan Silvia Kup",
    ano: "2022",
    logoCampeonato: "logoSilviaKupRed2022.png",
    corBkg: "#e9e9e9",
    corHead: "#bc0202",
    corRow: "#c7c7c7",
    corTxt: "#bc0202",
    idPiloto: "",
    nomePiloto: "Thiago Alves da Silva",
    idPsn: "Thiago_Wolf",
    totalPontos: 15,
    posicao: "14",
  },
  {
    nomeCampeonato: "Nissan Silvia Kup",
    ano: "2022",
    logoCampeonato: "logoSilviaKupRed2022.png",
    corBkg: "#e9e9e9",
    corHead: "#bc0202",
    corRow: "#c7c7c7",
    corTxt: "#bc0202",
    idPiloto: "",
    nomePiloto: "Marco Antonio Soares",
    idPsn: "CRS_BillyBizzuca",
    totalPontos: 0,
    posicao: "15",
  },
];
